name             'docker-swarm-cookbook'
maintainer       'Rodrigo Reis'
maintainer_email 'rodrigo.reis@gmail.com'
license          'All rights reserved'
description      'Installs/Configures docker-swarm-cookbook'
long_description 'Installs/Configures docker-swarm-cookbook'
version          '0.1.0'

depends          'docker', '~> 2.0'
depends          'etcd'
depends          'python'
depends          'aws'